import os
import codecs

html_path = 'c:/Projects/OnlyOffice/app/editors/web-apps/apps/documenteditor/main/index_loader.html'

with codecs.open(html_path, 'r', 'utf8') as f:
    text = f.read()

script_to_inject = """
<script>
// UI SURGERY 
document.addEventListener("DOMContentLoaded", function() {
    var observer = new MutationObserver(function(mutations, me) {
        // Wait for the main UI components to be generated by app.js
        var boxHeader = document.querySelector(".box-header") || document.querySelector("#box-header") || document.getElementById("header");
        var tabContainer = document.querySelector(".toolbar-tabs-container") || document.querySelector(".toolbar-tabs") || document.querySelector("ul[role='tablist']");
        
        if (boxHeader && tabContainer) {
            console.log("OnlyOffice UI Surgery Initialized");
            me.disconnect(); // Stop observing once we find the UI
            
            // 1. Remove unwanted Tabs (Collaboration, Plugins, Protection)
            var badTabs = ["collaboration", "protection", "plugins", "ai", "ai-chat", "chat"];
            var tabs = tabContainer.querySelectorAll("li");
            tabs.forEach(function(t) {
                var tid = t.getAttribute("data-id") || t.id || "";
                badTabs.forEach(function(bt) {
                    if (tid.toLowerCase().indexOf(bt) !== -1) {
                        t.remove();
                    }
                });
            });
            
            // 2. Remove Clouds and Editing/Reviewing mode switchers
            var rightMenu = document.querySelector(".right-menu") || document.querySelector(".top-panel-right");
            if (rightMenu) {
                var modeSwitchers = rightMenu.querySelectorAll("[class*='mode-switcher'], [id*='mode'], [id*='clouds'], [class*='cloud']");
                modeSwitchers.forEach(function(el) { el.remove(); });
            }
            
            // 3. Move Save/Undo/Redo into the tabs bar
            var tools = boxHeader.querySelector(".header-tools") || document.querySelector(".header-left");
            if (tools && tabContainer.parentNode) {
                // Move tools to the left of the tabs
                tools.style.display = 'inline-flex';
                tools.style.alignItems = 'center';
                tools.style.marginRight = '15px';
                
                // Keep the icon buttons, maybe trim extra spacing
                
                var topRowWrapper = tabContainer.parentNode;
                topRowWrapper.style.display = 'flex';
                topRowWrapper.style.alignItems = 'center';
                topRowWrapper.insertBefore(tools, tabContainer);
            }
            
            // 4. Move Title into the tabs bar, aligned left before the right menu
            var titleBox = boxHeader.querySelector(".header-title") || boxHeader.querySelector("#document-title") || boxHeader.querySelector(".title-text");
            if (titleBox && rightMenu) {
                titleBox.style.marginLeft = 'auto'; // push right
                titleBox.style.marginRight = '20px'; // gap before right menu
                titleBox.style.maxWidth = '300px';
                titleBox.style.overflow = 'hidden';
                titleBox.style.textOverflow = 'ellipsis';
                titleBox.style.display = 'inline-block';
                
                rightMenu.parentNode.insertBefore(titleBox, rightMenu);
            }
            
            // 5. Delete the entire top header bar and move everything up!
            boxHeader.remove();
            
            // Adjust the layout to reclaim the empty space
            var mainContent = document.querySelector(".main-panel") || document.querySelector("#mainpnl") || document.querySelector(".app-body");
            if (mainContent) {
                mainContent.style.top = '40px'; // The second bar is usually 40px
            }
        }
    });
    
    // Start observing the body for injected UI
    observer.observe(document.body, { childList: true, subtree: true });
});
</script>
"""

if "UI SURGERY" not in text:
    text = text.replace("</head>", script_to_inject + "\n</head>")
    with codecs.open(html_path, 'w', 'utf8') as f:
        f.write(text)
    print("UI Surgery script injected successfully into index_loader.html")
else:
    print("UI Surgery script already exists.")
