export const openrouterInfo = {
  name: "OpenRouter",
  baseUrl: "https://openrouter.ai/api/v1",
  modelFilters: [
    "openai/gpt-5.2",
    "anthropic/claude-haiku-4.5",
    "anthropic/claude-sonnet-4.5",
    "anthropic/claude-opus-4.5",
    "x-ai/grok-4",
    "x-ai/grok-4.1-fast",
    "qwen/qwen3-235b-a22b-2507",
    "qwen/qwen3-max",
    "deepseek/deepseek-v3.1-terminus",
    "google/gemini-3-pro-preview",
    "google/gemini-3-flash-preview",
  ],
  modelNames: {
    "openai/gpt-5.2": "GPT-5.2",
    "anthropic/claude-haiku-4.5": "Claude Haiku 4.5",
    "anthropic/claude-sonnet-4.5": "Claude Sonnet 4.5",
    "anthropic/claude-opus-4.5": "Claude Opus 4.5",
    "x-ai/grok-4": "Grok 4",
    "x-ai/grok-4.1-fast": "Grok 4.1 Fast",
    "qwen/qwen3-235b-a22b-2507": "Qwen3",
    "qwen/qwen3-max": "Qwen3 Max",
    "deepseek/deepseek-v3.1-terminus": "DeepSeek V3.1 Terminus",
    "google/gemini-3-pro-preview": "Gemini 3 Pro Preview",
    "google/gemini-3-flash-preview": "Gemini 3 Flash Preview",
  } as Record<string, string>,
  reasoningModels: [
    "openai/gpt-5.2",
    "anthropic/claude-sonnet-4.5",
    "anthropic/claude-opus-4.5",
    "x-ai/grok-4.1-fast",
    "qwen/qwen3-235b-a22b-2507",
    "qwen/qwen3-max",
    "deepseek/deepseek-v3.1-terminus",
    "google/gemini-3-pro-preview",
    "google/gemini-3-flash-preview",
  ],
};
